---
title: "Merced River"
author: "sadie"
date: "December 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readxl)
library(cvpiaHabitat)
```

## Instream Spawning and Rearing Habiat

> **Data Source:**   TODO
> [FWS 1996 and MID 2013](https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/FWS1996_AmericanRiverSpawningFinalReport.pdf)
> <https://flowwest.github.io/cvpiaHabitat/reference/merced_river_instream.html>

Mark Gard instructed us to use cells A18:E48 in the 'Merced' tab within his 'IFIMWUA.xlsx'.
Units are in square feet per 1000 feet.


```{r}
merced_river_instream <- read_excel('data-raw/mark_gard_data/IFIMWUA.xlsx', 
           range = "A18:E48", sheet = 'Merced') %>% 
  rename(flow_cfs = Flow, FR_spawning_wua = Spawning, FR_fry_wua = `Fry Rearing`, 
         FR_juv_wua = `Juv Rearing`, adult_steelhead_wua = `adult steelhead`) %>% 
  mutate(watershed = 'Merced River')

merced_river_instream
# devtools::use_data(merced_river_instream, overwrite = TRUE)
```

