---
title: "Calaveras River"
author: "sadie"
date: "December 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readxl)
library(cvpiaHabitat)
```

## Instream Spawning and Rearing Habiat

> **Data Source:**   TODO
> [FishBio and Payne 2009](https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/FishBio_Payne2009_CalaverasInstreamFlowStudy.pdf)
> <https://flowwest.github.io/cvpiaHabitat/reference/calaveras_river_instream.html>

Mark Gard instructed us to use cells A2:D12 for steelhead rearing in the 'Calaveras' tab within his 'IFIMWUA.xlsx'. Units are square feet per 1000 ft.

```{r}

calaveras <- read_excel('data-raw/mark_gard_data/IFIMWUA.xlsx', 
                        range = "A2:D12", sheet = 'Calaveras') 


calaveras_river_instream <- calaveras %>% 
  mutate(watershed = 'Calaveras River') %>% 
  rename(flow_cfs = Flow, ST_spawn_wua = 'Spawning', ST_fry_wua = `Fry Rearing`,
         ST_juv_wua = `Juv Rearing`)

calaveras_river_instream
# devtools::use_data(calaveras_river_instream, overwrite = TRUE)
```

