---
title: "Tuolumne River"
author: "sadie"
date: "December 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readxl)
library(cvpiaHabitat)
```

## Instream Spawning and Rearing Habiat

> **Data Source:**   TODO
> [Flo2D model by Stillwater 2014](https://s3-us-west-2.amazonaws.com/cvpiahabitat-r-package/cvpia-sit-model-inputs/Stillwater2010_Tuolumne_P-2299-075_71_DP_FLA_AttC_StudyRept_IFIM_AppA-H_140428.pdf)
> <https://flowwest.github.io/cvpiaHabitat/reference/tuolumne_river_instream.html>

Mark Gard instructed us to use cells A2:H32 in the 'Tuolumne' tab within his 'IFIMWUA.xlsx'.
Units are in square feet per 1000 feet.


```{r}
# merced_river_instream <-
tuolumne_river_instream <- read_excel('data-raw/mark_gard_data/IFIMWUA.xlsx', 
                                      range = "A2:H32", sheet = 'Tuolumne') %>% 
  mutate(watershed = 'Tuolumne River') %>% 
  select(flow_cfs = `Simulated\nDischarge\n(cfs)`, FR_spawn_wua = `Chinook\nSpawning`,
         FR_fry_wua = `Chinook\nFry`, FR_juv_wua = `Chinook\nJuvenile`, 
         ST_spawn_wua = `O. mykiss\nSpawning`, ST_fry_wua = `O. mykiss\nFry`, 
         ST_juv_wua = `O. mykiss\nJuvenile`, ST_adult_wua = `O. mykiss\nAdult`, watershed)

tuolumne_river_instream
# devtools::use_data(tuolumne_river_instream, overwrite = TRUE)
```

