---
title: "Bypasses"
author: "[Sadie Gill](mailto:sgill@flowwest.com), [Mark Tompkins](mailto:mtompkins@flowwest.com)"
date: "July 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(tidyverse)
library(readxl)
library(cvpiaHabitat)
```

```{r}
# 1 sq ft = 0.092903 sq meters
sutter1 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 2) %>% 
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Sutter_Bypass_1_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Sutter Bypass 1') %>%
  select(flow_cfs, total_sq_meters, bypass)

sutter2 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 3) %>%
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Sutter_Bypass_2_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Sutter Bypass 2') %>%
  select(flow_cfs, total_sq_meters, bypass)

sutter3 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 4) %>%
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Sutter_Bypass_3_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Sutter Bypass 3') %>%
  select(flow_cfs, total_sq_meters, bypass)

sutter4 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 5) %>%
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Sutter_Bypass_4_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Sutter Bypass 4') %>%
  select(flow_cfs, total_sq_meters, bypass)

yolo1 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 6) %>%
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Yolo_Bypass_1_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Yolo Bypass 1') %>%
  select(flow_cfs, total_sq_meters, bypass)

yolo2 <- read_excel('data-raw/correigh_greene_data/River Rearing_Habitat vs flow.xls', sheet = 7) %>%
  mutate(flow_cfs = Flow_cfs,
         total_sq_meters = Yolo_Bypass_2_Pref11_TotlArea_Sq_ft * 0.092903,
         bypass = 'Yolo Bypass 2') %>%
  select(flow_cfs, total_sq_meters, bypass)

sutter_bypass_habitat <- bind_rows(sutter1, sutter2, sutter3, sutter4) %>% 
  spread(bypass, total_sq_meters) 

yolo_bypass_habitat <- bind_rows(yolo1, yolo2) %>% 
  spread(bypass, total_sq_meters)

# devtools::use_data(sutter_bypass_habitat)
# devtools::use_data(yolo_bypass_habitat)
```
